identifier: k2w2b3v5d0gb39c5
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: angular-router-sample
homeFolder: /Users/I536116/Desktop/SAP/spartacus-performance/angular-router-sample
distFolder: dist/angular-router-sample
outDir: >-
  /Users/I536116/Desktop/SAP/spartacus-performance/angular-router-sample/dist/static
handle404: ''
allowErrorCollect: false
